"""Add relation for period item

Revision ID: 1c53ccb32d06
Revises: 272c27ddef15
Create Date: 2015-06-21 17:10:23.927912

"""

# revision identifiers, used by Alembic.
revision = '1c53ccb32d06'
down_revision = '272c27ddef15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentperiod', sa.Column('rent_period_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rentperiod', 'rent_periods', ['rent_period_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentperiod', type_='foreignkey')
    op.drop_column('rentperiod', 'rent_period_id')
    ### end Alembic commands ###
