"""Add dates for period item

Revision ID: 272c27ddef15
Revises: 29813c12e3f6
Create Date: 2015-06-21 15:59:16.829366

"""

# revision identifiers, used by Alembic.
revision = '272c27ddef15'
down_revision = '29813c12e3f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent_periods', 'end_date')
    op.add_column('rentperiod', sa.Column('begin_date', sa.Date(), nullable=False))
    op.add_column('rentperiod', sa.Column('end_date', sa.Date(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentperiod', 'end_date')
    op.drop_column('rentperiod', 'begin_date')
    op.add_column('rent_periods', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
