"""Add unique for email field

Revision ID: 28399ddf5a49
Revises: 9d6ea8c5c73
Create Date: 2015-06-28 23:37:41.606034

"""

# revision identifiers, used by Alembic.
revision = '28399ddf5a49'
down_revision = '9d6ea8c5c73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
