"""Add period item

Revision ID: 29813c12e3f6
Revises: 3d5e61d6c047
Create Date: 2015-06-21 15:37:35.948317

"""

# revision identifiers, used by Alembic.
revision = '29813c12e3f6'
down_revision = '3d5e61d6c047'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentperiod',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summ', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_payment_status', sa.Enum('wait', 'payed', name='rent_period_payment_statuses'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'rent_periods', 'payment_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'rent_periods', sa.Column('payment_status', postgresql.ENUM(u'wait', u'payed', name='payment_statuses'), autoincrement=False, nullable=False))
    op.drop_table('rentperiod')
    ### end Alembic commands ###
