"""Add is_active for users

Revision ID: 313526babd4f
Revises: 363d40f9480f
Create Date: 2015-06-29 00:03:26.103824

"""

# revision identifiers, used by Alembic.
revision = '313526babd4f'
down_revision = '363d40f9480f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###
