"""Remove is_active for users

Revision ID: 340f241704e2
Revises: 313526babd4f
Create Date: 2015-06-29 00:07:15.351725

"""

# revision identifiers, used by Alembic.
revision = '340f241704e2'
down_revision = '313526babd4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
