"""Add periods

Revision ID: 3d5e61d6c047
Revises: bbb03d228a1
Create Date: 2015-05-11 22:24:33.509869

"""

# revision identifiers, used by Alembic.
revision = '3d5e61d6c047'
down_revision = 'bbb03d228a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_periods',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('summ', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('wait', 'payed', name='payment_statuses'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='period_statuses'), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['renters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_periods')
    ### end Alembic commands ###
